export const gpuBrandList = [
    "NVIDIA",
    "AMD",
    "Intel",
    "ARM",
    "Qualcomm",
    "Apple",
    "Imagination Technologies",
    "Broadcom",
    "NXP",
    "Marvell",
    "Freescale",
    "Texas Instruments",
    "Cirrus Logic",
    "Wolfson Microelectronics",
    "Sigma Designs",
    "Cavium",
    "Marvell",
    "Qualcomm"]; 